name: Publish to PyPI

on:
  push:
    paths:
      - dev/values/programmatic_variables/version
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.0
      with:
      python_version: "3.10"
      pypi_token: ${{ secrets.PYPI_TOKEN }}
